# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ToDo_Reminder' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ToDo_Reminder

	pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
	pod 'Resolver'
  pod 'Disk', '~> 0.6.4'



  target 'ToDo_ReminderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ToDo_ReminderUITests' do
    # Pods for testing
  end

end
